"""Add the fixed DATA-002 domain schema.

This migration uses fixed operations so a future model cannot silently alter
an already deployed schema.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_domain_models"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
TS = sa.DateTime(timezone=True)
NOW = sa.text("CURRENT_TIMESTAMP")
JSON = sa.JSON()


def upgrade() -> None:
    op.create_table("profiles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("cv_text", sa.Text()), sa.Column("cv_filename", sa.String(255)), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("skills", JSON, nullable=False), sa.Column("experience", JSON, nullable=False), sa.Column("education", JSON, nullable=False), sa.Column("languages", JSON, nullable=False), sa.Column("created_at", TS, nullable=False, server_default=NOW), sa.Column("updated_at", TS, nullable=False, server_default=NOW))
    op.create_table("sources", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False, unique=True), sa.Column("kind", sa.String(30), nullable=False, server_default="career_page"), sa.Column("base_url", sa.String(2048)), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("config", JSON, nullable=False), sa.Column("terms_url", sa.String(2048)), sa.Column("robots_checked_at", TS), sa.Column("created_at", TS, nullable=False, server_default=NOW), sa.Column("updated_at", TS, nullable=False, server_default=NOW))
    op.create_table("profile_preferences", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("profile_id", sa.Integer(), sa.ForeignKey("profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("target_roles", JSON, nullable=False), sa.Column("locations", JSON, nullable=False), sa.Column("modalities", JSON, nullable=False), sa.Column("salary_min", sa.Float()), sa.Column("salary_currency", sa.String(3)), sa.Column("work_authorization", JSON, nullable=False), sa.Column("willing_to_relocate", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("weights", JSON, nullable=False), sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", TS, nullable=False, server_default=NOW), sa.Column("updated_at", TS, nullable=False, server_default=NOW))
    op.create_table("jobs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_id", sa.Integer(), sa.ForeignKey("sources.id", ondelete="SET NULL")), sa.Column("title", sa.String(500), nullable=False), sa.Column("company", sa.String(300), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("description_url", sa.String(2048), nullable=False), sa.Column("application_url", sa.String(2048)), sa.Column("canonical_url", sa.String(2048), nullable=False), sa.Column("fingerprint", sa.String(128), nullable=False), sa.Column("location", sa.String(300)), sa.Column("region", sa.String(40), nullable=False, server_default="other"), sa.Column("modality", sa.String(20), nullable=False, server_default="unknown"), sa.Column("salary_min", sa.Float()), sa.Column("salary_max", sa.Float()), sa.Column("salary_currency", sa.String(3)), sa.Column("published_at", sa.Date()), sa.Column("detected_at", TS, nullable=False, server_default=NOW), sa.Column("checked_at", TS, nullable=False, server_default=NOW), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("metadata_json", JSON, nullable=False))
    op.create_table("pipeline_executions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("run_id", sa.String(36), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False, server_default="running"), sa.Column("started_at", TS, nullable=False, server_default=NOW), sa.Column("finished_at", TS), sa.Column("metrics", JSON, nullable=False), sa.Column("error", sa.Text()), sa.Column("created_at", TS, nullable=False, server_default=NOW), sa.Column("updated_at", TS, nullable=False, server_default=NOW))
    op.create_table("job_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("description_url", sa.String(2048), nullable=False), sa.Column("application_url", sa.String(2048)), sa.Column("captured_at", TS, nullable=False, server_default=NOW), sa.Column("content_hash", sa.String(128), nullable=False), sa.UniqueConstraint("job_id", "content_hash", name="uq_job_snapshot_hash"))
    op.create_table("evaluations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("profile_id", sa.Integer(), sa.ForeignKey("profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("score", sa.Float(), nullable=False), sa.Column("ruleset_version", sa.String(50), nullable=False), sa.Column("model_version", sa.String(100)), sa.Column("score_breakdown", JSON, nullable=False), sa.Column("matches", JSON, nullable=False), sa.Column("gaps", JSON, nullable=False), sa.Column("exclusions", JSON, nullable=False), sa.Column("recommendations", JSON, nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="pending"), sa.Column("evaluated_at", TS, nullable=False, server_default=NOW))
    op.create_table("source_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("execution_id", sa.Integer(), sa.ForeignKey("pipeline_executions.id", ondelete="CASCADE"), nullable=False), sa.Column("source_id", sa.Integer(), sa.ForeignKey("sources.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("jobs_found", sa.Integer(), nullable=False, server_default="0"), sa.Column("error", sa.Text()), sa.Column("started_at", TS, nullable=False, server_default=NOW), sa.Column("finished_at", TS))
    op.create_table("notion_syncs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("external_id", sa.String(100), nullable=False), sa.Column("state", sa.String(20), nullable=False, server_default="pending"), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_error", sa.Text()), sa.Column("reconciliation", JSON, nullable=False), sa.Column("synced_at", TS), sa.UniqueConstraint("job_id", name="uq_notion_sync_job"), sa.UniqueConstraint("external_id", name="uq_notion_sync_external_id"))
    for table, indexes in {"profile_preferences": [("ix_profile_preferences_profile_id", ["profile_id"]), ("ix_profile_preferences_current", ["profile_id", "is_current"])], "jobs": [("ix_jobs_source_id", ["source_id"]), ("ix_jobs_canonical_url", ["canonical_url"]), ("ix_jobs_fingerprint", ["fingerprint"]), ("ix_jobs_region", ["region"]), ("ix_jobs_status", ["status"]), ("ix_jobs_detected_at", ["detected_at"]), ("ix_jobs_published_at", ["published_at"])], "job_snapshots": [("ix_job_snapshots_job_id", ["job_id"]), ("ix_job_snapshots_captured_at", ["captured_at"])], "evaluations": [("ix_evaluations_job_id", ["job_id"]), ("ix_evaluations_profile_id", ["profile_id"]), ("ix_evaluations_score", ["score"]), ("ix_evaluations_status", ["status"]), ("ix_evaluations_evaluated_at", ["evaluated_at"])], "pipeline_executions": [("ix_pipeline_executions_status", ["status"]), ("ix_pipeline_executions_started_at", ["started_at"])], "source_runs": [("ix_source_runs_status", ["status"]), ("ix_source_runs_started_at", ["started_at"])], "notion_syncs": [("ix_notion_syncs_job_id", ["job_id"]), ("ix_notion_syncs_state", ["state"])]}.items():
        for name, columns in indexes:
            op.create_index(name, table, columns)


def downgrade() -> None:
    for name, table in [("ix_notion_syncs_state", "notion_syncs"), ("ix_notion_syncs_job_id", "notion_syncs"), ("ix_source_runs_started_at", "source_runs"), ("ix_source_runs_status", "source_runs"), ("ix_pipeline_executions_started_at", "pipeline_executions"), ("ix_pipeline_executions_status", "pipeline_executions"), ("ix_evaluations_evaluated_at", "evaluations"), ("ix_evaluations_status", "evaluations"), ("ix_evaluations_score", "evaluations"), ("ix_evaluations_profile_id", "evaluations"), ("ix_evaluations_job_id", "evaluations"), ("ix_job_snapshots_captured_at", "job_snapshots"), ("ix_job_snapshots_job_id", "job_snapshots"), ("ix_jobs_published_at", "jobs"), ("ix_jobs_detected_at", "jobs"), ("ix_jobs_status", "jobs"), ("ix_jobs_region", "jobs"), ("ix_jobs_fingerprint", "jobs"), ("ix_jobs_canonical_url", "jobs"), ("ix_jobs_source_id", "jobs"), ("ix_profile_preferences_current", "profile_preferences"), ("ix_profile_preferences_profile_id", "profile_preferences")]:
        op.drop_index(name, table_name=table)
    for table in ("notion_syncs", "source_runs", "evaluations", "job_snapshots", "pipeline_executions", "jobs", "profile_preferences", "sources", "profiles"):
        op.drop_table(table)
